<?php

namespace Database\Seeders;

use App\Models\AdmissionFormField;
use Illuminate\Database\Seeder;

class AdmissionFormFieldSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fields = [
            // Step 1: Shaxsiy ma'lumotlar
            [
                'field_key' => 'step1_heading',
                'field_type' => 'heading',
                'label_uz' => 'Shaxsiy ma\'lumotlar',
                'label_ru' => 'Личные данные',
                'label_en' => 'Personal Information',
                'step' => 1,
                'sort_order' => 0,
            ],
            [
                'field_key' => 'last_name',
                'field_type' => 'text',
                'label_uz' => 'Familiya',
                'label_ru' => 'Фамилия',
                'label_en' => 'Last Name',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 1,
                'validation_rules' => ['string', 'max:255'],
            ],
            [
                'field_key' => 'first_name',
                'field_type' => 'text',
                'label_uz' => 'Ism',
                'label_ru' => 'Имя',
                'label_en' => 'First Name',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 2,
                'validation_rules' => ['string', 'max:255'],
            ],
            [
                'field_key' => 'middle_name',
                'field_type' => 'text',
                'label_uz' => 'Otasining ismi',
                'label_ru' => 'Отчество',
                'label_en' => 'Middle Name',
                'is_required' => false,
                'step' => 1,
                'sort_order' => 3,
            ],
            [
                'field_key' => 'birth_date',
                'field_type' => 'date',
                'label_uz' => 'Tug\'ilgan sana',
                'label_ru' => 'Дата рождения',
                'label_en' => 'Birth Date',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 4,
                'validation_rules' => ['before:today'],
            ],
            [
                'field_key' => 'gender',
                'field_type' => 'select',
                'label_uz' => 'Jinsi',
                'label_ru' => 'Пол',
                'label_en' => 'Gender',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 5,
                'options' => ['male' => 'Erkak', 'female' => 'Ayol'],
            ],
            [
                'field_key' => 'jshshir',
                'field_type' => 'text',
                'label_uz' => 'JSHSHIR',
                'label_ru' => 'ПИНФЛ',
                'label_en' => 'JSHSHIR',
                'placeholder' => '14 ta raqam',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 6,
                'validation_rules' => ['string', 'size:14', 'regex:/^[0-9]+$/', 'unique:admission_applications,jshshir'],
            ],
            [
                'field_key' => 'passport_series',
                'field_type' => 'text',
                'label_uz' => 'Pasport seriya',
                'label_ru' => 'Серия паспорта',
                'label_en' => 'Passport Series',
                'placeholder' => 'AB',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 7,
                'validation_rules' => ['string', 'size:2', 'regex:/^[A-Z]+$/'],
            ],
            [
                'field_key' => 'passport_number',
                'field_type' => 'text',
                'label_uz' => 'Pasport raqam',
                'label_ru' => 'Номер паспорта',
                'label_en' => 'Passport Number',
                'placeholder' => '1234567',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 8,
                'validation_rules' => ['string', 'size:7', 'regex:/^[0-9]+$/'],
            ],
            // Contact info heading
            [
                'field_key' => 'contact_heading',
                'field_type' => 'heading',
                'label_uz' => 'Aloqa ma\'lumotlari',
                'label_ru' => 'Контактные данные',
                'label_en' => 'Contact Information',
                'step' => 1,
                'sort_order' => 9,
            ],
            [
                'field_key' => 'phone',
                'field_type' => 'phone',
                'label_uz' => 'Telefon raqam',
                'label_ru' => 'Номер телефона',
                'label_en' => 'Phone Number',
                'placeholder' => '+998901234567',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 10,
            ],
            [
                'field_key' => 'email',
                'field_type' => 'email',
                'label_uz' => 'Email',
                'label_ru' => 'Электронная почта',
                'label_en' => 'Email',
                'placeholder' => 'email@example.com',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 11,
                'validation_rules' => ['unique:admission_applications,email'],
            ],
            [
                'field_key' => 'region',
                'field_type' => 'text',
                'label_uz' => 'Viloyat',
                'label_ru' => 'Область',
                'label_en' => 'Region',
                'placeholder' => 'Samarqand viloyati',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 12,
            ],
            [
                'field_key' => 'district',
                'field_type' => 'text',
                'label_uz' => 'Tuman/Shahar',
                'label_ru' => 'Район/Город',
                'label_en' => 'District/City',
                'placeholder' => 'Samarqand shahri',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 13,
            ],
            [
                'field_key' => 'address',
                'field_type' => 'textarea',
                'label_uz' => 'To\'liq manzil',
                'label_ru' => 'Полный адрес',
                'label_en' => 'Full Address',
                'placeholder' => 'Ko\'cha, uy raqami',
                'is_required' => true,
                'step' => 1,
                'sort_order' => 14,
            ],

            // Step 2: Ta'lim ma'lumotlari
            [
                'field_key' => 'step2_heading',
                'field_type' => 'heading',
                'label_uz' => 'Ta\'lim ma\'lumotlari',
                'label_ru' => 'Сведения об образовании',
                'label_en' => 'Education Information',
                'step' => 2,
                'sort_order' => 0,
            ],
            [
                'field_key' => 'education_type',
                'field_type' => 'select',
                'label_uz' => 'Ta\'lim turi',
                'label_ru' => 'Тип образования',
                'label_en' => 'Education Type',
                'is_required' => true,
                'step' => 2,
                'sort_order' => 1,
                'options' => [
                    'school' => 'Maktab',
                    'college' => 'Kollej',
                    'lyceum' => 'Litsey',
                    'bachelor' => 'Bakalavr',
                ],
            ],
            [
                'field_key' => 'education_name',
                'field_type' => 'text',
                'label_uz' => 'O\'quv muassasa nomi',
                'label_ru' => 'Название учебного заведения',
                'label_en' => 'Educational Institution Name',
                'placeholder' => 'Masalan: 1-sonli umumiy o\'rta ta\'lim maktabi',
                'is_required' => true,
                'step' => 2,
                'sort_order' => 2,
            ],
            [
                'field_key' => 'graduation_year',
                'field_type' => 'text',
                'label_uz' => 'Tamomlagan yili',
                'label_ru' => 'Год окончания',
                'label_en' => 'Graduation Year',
                'is_required' => true,
                'step' => 2,
                'sort_order' => 3,
                'validation_rules' => ['integer', 'min:2000', 'max:2030'],
            ],
            [
                'field_key' => 'dtm_score',
                'field_type' => 'text',
                'label_uz' => 'DTM bali',
                'label_ru' => 'Балл ДТМ',
                'label_en' => 'DTM Score',
                'placeholder' => 'Agar mavjud bo\'lsa',
                'is_required' => false,
                'step' => 2,
                'sort_order' => 4,
                'validation_rules' => ['integer', 'min:0', 'max:189'],
            ],

            // Step 3: Yo'nalish tanlash
            [
                'field_key' => 'step3_heading',
                'field_type' => 'heading',
                'label_uz' => 'Yo\'nalish tanlash',
                'label_ru' => 'Выбор направления',
                'label_en' => 'Program Selection',
                'step' => 3,
                'sort_order' => 0,
            ],
            [
                'field_key' => 'faculty_id',
                'field_type' => 'select',
                'label_uz' => 'Fakultet',
                'label_ru' => 'Факультет',
                'label_en' => 'Faculty',
                'is_required' => true,
                'step' => 3,
                'sort_order' => 1,
                'options' => [], // Will be filled dynamically from database
            ],
            [
                'field_key' => 'specialty_id',
                'field_type' => 'select',
                'label_uz' => 'Yo\'nalish/Mutaxassislik',
                'label_ru' => 'Направление/Специальность',
                'label_en' => 'Specialty',
                'is_required' => true,
                'step' => 3,
                'sort_order' => 2,
                'options' => [], // Will be filled dynamically from database
            ],
            [
                'field_key' => 'education_form',
                'field_type' => 'select',
                'label_uz' => 'Ta\'lim shakli',
                'label_ru' => 'Форма обучения',
                'label_en' => 'Education Form',
                'is_required' => true,
                'step' => 3,
                'sort_order' => 3,
                'options' => [
                    'kunduzgi' => 'Kunduzgi',
                    'sirtqi' => 'Sirtqi',
                    'kechki' => 'Kechki',
                ],
            ],
            [
                'field_key' => 'education_language',
                'field_type' => 'select',
                'label_uz' => 'Ta\'lim tili',
                'label_ru' => 'Язык обучения',
                'label_en' => 'Education Language',
                'is_required' => true,
                'step' => 3,
                'sort_order' => 4,
                'options' => [
                    'uz' => 'O\'zbek',
                    'ru' => 'Rus',
                    'en' => 'Ingliz',
                ],
            ],

            // Step 4: Hujjatlar
            [
                'field_key' => 'step4_heading',
                'field_type' => 'heading',
                'label_uz' => 'Hujjatlar yuklash',
                'label_ru' => 'Загрузка документов',
                'label_en' => 'Upload Documents',
                'step' => 4,
                'sort_order' => 0,
            ],
            [
                'field_key' => 'photo',
                'field_type' => 'file',
                'label_uz' => '3x4 rasm',
                'label_ru' => 'Фото 3x4',
                'label_en' => '3x4 Photo',
                'is_required' => true,
                'step' => 4,
                'sort_order' => 1,
                'file_config' => [
                    'max_size' => 2048,
                    'allowed_extensions' => ['jpg', 'jpeg', 'png'],
                    'storage_path' => 'admission/photos',
                ],
            ],
            [
                'field_key' => 'passport_copy',
                'field_type' => 'file',
                'label_uz' => 'Pasport nusxasi',
                'label_ru' => 'Копия паспорта',
                'label_en' => 'Passport Copy',
                'is_required' => true,
                'step' => 4,
                'sort_order' => 2,
                'file_config' => [
                    'max_size' => 5120,
                    'allowed_extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
                    'storage_path' => 'admission/passports',
                ],
            ],
            [
                'field_key' => 'diploma_copy',
                'field_type' => 'file',
                'label_uz' => 'Diplom/Attestat',
                'label_ru' => 'Диплом/Аттестат',
                'label_en' => 'Diploma/Certificate',
                'is_required' => true,
                'step' => 4,
                'sort_order' => 3,
                'file_config' => [
                    'max_size' => 5120,
                    'allowed_extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
                    'storage_path' => 'admission/diplomas',
                ],
            ],
            [
                'field_key' => 'certificate_copy',
                'field_type' => 'file',
                'label_uz' => 'Sertifikat (agar bo\'lsa)',
                'label_ru' => 'Сертификат (если есть)',
                'label_en' => 'Certificate (if available)',
                'is_required' => false,
                'step' => 4,
                'sort_order' => 4,
                'file_config' => [
                    'max_size' => 5120,
                    'allowed_extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
                    'storage_path' => 'admission/certificates',
                ],
            ],
        ];

        foreach ($fields as $fieldData) {
            AdmissionFormField::updateOrCreate(
                ['field_key' => $fieldData['field_key']],
                array_merge($fieldData, ['is_active' => true])
            );
        }
    }
}
